### ISSUE TITLE
look into FREERTOS

### ISSUE THREAD

**Issue by nerdoug** [va3wam/hexBot#11]
https://github.com/va3wam/hexBot/blob/b14a6327b650fce4c8ffc3d2039137bf4c722253/src/main.cpp#L44-L44

**Comment by nerdoug** [comment]
pre-emptive multitasking would remove a lot of the constraints on how we structure and call routines. There would no longer be a need to "stay out of the way" of the 20 millisecond leg movement task, because it would simply pre-empt what ever else might happen to be running.

**Comment by theAgingApprentice** [comment]
Going to drop this issue for now. If we change our minds we can create a new issue.
