### ISSUE TITLE
Monitor the current and voltage to the motor controllers

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#119]
Be able to monitor the current and voltage going to the motor controllers. This will allow us to power down when their are strange spikes in the current.

**Comment by theAgingApprentice** [comment]
We are debating if we should do this. Very nice to have but may not be practical to implement.

**Comment by nerdoug** [comment]
We've decided we need to do this in order to have reliable startup of the servos. Since this is included in issue 157, I'm closing this one.
