### ISSUE TITLE
Motors can lock up for no apparent reason

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#122]
It has been noted that sometimes some of the servo motors lock up so that even when there is no power they cannot be moved by hand. This seems to happen most often to the hip motors. It seems that when power is applied the motors behave fine but we should still figure out what is causing this.

**Comment by nerdoug** [comment]
Doug has never observed this, although it may have happened and not been detected.

**Comment by theAgingApprentice** [comment]
Andrew is the only one who has seen this. We think that this is also tied to the power up sequence which is being tracked in a different ticket.

**Comment by theAgingApprentice** [comment]
That other ticket is #120

**Comment by theAgingApprentice** [comment]
Duplicate issue. Closing.
