### ISSUE TITLE
trim the list of 27 labels available for new issues

### ISSUE THREAD

**Issue by nerdoug** [va3wam/hexBot#130]
we've never used at least half of the labels, and triming the list would reduce the scrolling needed to find the ones we actually do, or might, use. Suggest removing:
effort 1
effort 2
effort 3
effort 4
effort 5
effort 6
good firts issue
state approved
state blocked
type discussion
type feature  (since we're using enhancement instead)
type security
work complex
work complicated
work obvious

It would be ideal if the 3 or 4 labels we use frequently could appear at the top of the list.

**Comment by theAgingApprentice** [comment]
Removed requested items. Not sure how to change order but will investigate.
