### ISSUE TITLE
Update MQTT help command output

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#139]
Ensure that the MQTT help command output is updated to include something about the flow messages. Perhaps include a link to the available documents.

**Comment by nerdoug** [comment]
The following chart shows all MQTT commands which need to be covered by the help command.

![image](https://user-images.githubusercontent.com/10327266/167319101-a99f5d8b-ba59-4deb-b20b-2b5b591dd518.png)

**Comment by nerdoug** [comment]
added the MQTT commands to the help command MQTT output. Rather than describe all the Flow sub-commands, I included a reference to section 6 of 
>     ...hexbot/docs/MQTT scripts/creating-flows.odt
