### ISSUE TITLE
Add robot specific boot up logic

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#173]
Make a dummy routine called setConfig() in the configDetails.cpp include file that executes at startup and gives as a place to set global variables based on Mac address.

**Comment by nerdoug** [comment]
There's now a routine called setupPerBotConfig() in flows.cpp. It's called from setup() in main. The only thing it does so far is set the software defined PWM values for each servo's center position to 299.

This was actually implemented under issue 162

In retrospect, I see that I didn't follow the plan of creating a routine called setConfig() in the configDetails.cpp include file. I can move the code there if that would be better.
