### ISSUE TITLE
Nail down universal coordinate values

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#38]
Decisions:
1. We are going to use a "robot wide" coordinate system.
2. The x axis runs along the spine, the y axis runs across the shoulders, the z axis is up and down.
3. The Robot origin is in the centre of the robot chassis (x,y) and at the same height as the origin of the legs (z).
4. +x is forward. +z is up, +y is his left

To do:
Using Fusion360 create a diagram that shows  
1. Angle that the toe on each leg is from the origin x,y
2. The x,y,z home coordinate for each leg toe (home means 0 servo angles)

**Comment by theAgingApprentice** [comment]
Home coordinates for each toe are:
Front left leg toe home coordinates: x=+18.63cm, y=+14.82cm,z=-10.56cm
Front right leg toe home coordinates: x=+18.63cm, y=-14.82cm,z=-10.56cm
Mid left leg toe home coordinates: x=0cm, y=+20.80cm,z=-10.56cm
Mid right leg toe home coordinates: x=0cm, y=-20.80cm,z=-10.56cm
Back left leg toe home coordinates: x=-18.63cm, y=+14.82cm,z=-10.56cm
Back right leg toe home coordinates: x=-18.63cm, y=-14.82cm,z=-10.56c

Angles for each leg are:
Front & Back Legs: 38.5d off x axis 
Mid Legs: 90d off  x axis 

Rough Diagram:
![hexbotTopViewDimensions](https://user-images.githubusercontent.com/79261479/140230924-15cf48b6-d42f-4004-bf0e-6f82538c9ebf.png)
m

**Comment by nerdoug** [comment]
home position coordinates given here are close to, but not quite the same as those in /docs/hex-coord-translations.ods, sheet "key locations" Not sure if the difference matters.

**Comment by theAgingApprentice** [comment]
Moving to a new chassis and new numbers will be published. Can clode this issue.
