### ISSUE TITLE
add ToeMoveAction to MOVE_LEG MQTT command
Assignees: @nerdoug
Labels: enhancement 

### ISSUE THREAD

**Issue by nerdoug** [va3wam/hexBot#56]
The last argument for the flow_go command controls what is done when hexbot is ready to move toes to the specified new position:
- actually feed the servos a PWM value to do the physical movement
- or, display information like the resulting local toe coords on the serial monitor.

This issue covers providing the same parameter controlled action for the MOVE_LEG command

**Comment by nerdoug** [comment]
while you're at it in this code, add an option to bypass the toe safety box mechanism, so we can carefully test what the movement limits are for each leg.

**Comment by theAgingApprentice** [comment]
We are removing this command so we can close this issue.
