### ISSUE TITLE
Investigate current and voltage getting to the motors

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#58]
Initial voltage readings indicate that not enough power is getting to the motor controller boards.

**Comment by nerdoug** [comment]
If we measure battery voltage, servo voltage and servo current, we'll need 3 analog to digital converters. ESP32 has 2 ADC controllers that support 18 ADC channels (with some restrictions) so we should be OK.

**Comment by nerdoug** [comment]
I have a number of mini-voltmeter devices that can be hooked up to some of the unused duplicated pins on each PCA9685 to give a real time display of the voltage gong to the servo. Will provide a couple of these to Andrew.
NOTE: These run off the circuit they attach to, and will go blank if the voltage goes below their minimum operating requirement. They handle 4.5 - 5.0 fine, but I have seen them blank out.

**Comment by theAgingApprentice** [comment]
Mini-voltage meters added on both bots. Closing issue.
