### ISSUE TITLE
The last servo moves slower than the rest

### ISSUE THREAD

**Issue by theAgingApprentice** [va3wam/hexBot#62]
We have a few theories about what may be happening.

1. The I2C bus' have a contention issue and separating onto different I2C buses will fix this.
2. The PCA9685 cannot handle the number of servos we are using in a timely fashion. To test this change the number of motors we are managing to confirm.
3. The software queue that the PCA9685 always handles the last servo command slower due to how it handles its queue. By dropping and raising the number of servos controlled we could confirm this is what is happening.

**Comment by nerdoug** [comment]
resolved in flow processing by:
- changing capacitor on PWM boards from 470 to 1000 micro Farads
- alternating servo commands across PWM boards
- reducing servo movement frame rate from 50 to 20 frames per second.

Some troubleshooting commands such as SSD don't have all these fixes, and may still show last servo misbehaviour.
