### ISSUE TITLE
Move_Leg cmd doesn't account for reversed mounting of knee and ankle servos on left and right side of robot

### ISSUE THREAD

**Issue by nerdoug** [va3wam/hexBot#86]
The conversion of a knee or ankle angle, in degrees, to a PWM value suitable for feeding to a servo is complicated by the fact that the knee and ankle servos are mounted differently on either side of the bot. Using Doug's leg numbering, the angles need to be negated before PWM conversion on legs 4, 5 and 6. This does not apply to the hip servo.

**Comment by theAgingApprentice** [comment]
Getting rig of move leg command so we can close this issue.
